### ISSUE TITLE
Run (or advise to run) `ldconfig` after `make install`

### ISSUE THREAD

**Issue by cemerick** [pantoniou/libfyaml#14]
Not running `ldconfig` after installing yields:

```
fy-tool: error while loading shared libraries: libfyaml-0.3.so.0: cannot open shared object file: No such file or directory
```

The install step should do this automatically, or documentation/README should be updated to indicate it as necessary.

**Comment by pantoniou** [comment]
Which platform is this? Both contemporary Linux and Mac OS X seem to not need it.

**Comment by cemerick** [comment]
True enough, my main desktop ubuntu install didn't require this, but installation in a common ubuntu docker image does:

```sh
# docker run -it ubuntu:18.04 bash
...
# apt install -y gcc autoconf automake libtool git make libltdl-dev pkg-config
# git clone https://github.com/pantoniou/libfyaml.git
# cd libfyaml
# ./bootstrap.sh
# ./configure
# make install
# fy-tool
fy-tool: error while loading shared libraries: libfyaml-0.3.so.0: cannot open shared object file: No such file or directory
# ldconfig
# fy-tool
missing yaml file to dump
```

**Comment by pantoniou** [comment]
Running ldconfig after an install is highly unusual since the default installation directories (/usr and /usr/local) are not user writable and require elevated permissions.

You don't have to do make install to run fy-tool, replacing the invocation line with ./src/fy-tool would work.

In a docker container you can add the ldconfig step easily enough.
